# Generated by Django 3.2.3 on 2021-06-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('description', models.CharField(default='', max_length=250)),
                ('image', models.ImageField(upload_to='Test')),
            ],
        ),
    ]
